name: GitHub metrics as SVG image
on:
  schedule: [{ cron: "0 0 * * *" }]
  push:
    branches: [ master ]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Asia/Seoul
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: no
          plugin_habits_charts: yes
